const cadastros = [
    {
      id: "01",
      nome: "João da Silva Souza Ferreira Villa",
      numero_inscricao: "001",
      nascimento: "1980-10-02",
      cpf: "123.456.789-00",
      rg: "1234567",
      endereco: "Rua das Flores, 123, Centro",
      telefone: "(11) 98765-4321",
      estado_civil: "Casado",
      tem_filho: "sim",
      pcds: "não",
      quantidade_filhos: "2",
      reside_mais_um_ano: "sim",
      is_pcd: "não",
      sistema_carcerario: "não",
      etnia: "branco",
      dependentes: "sim",
      desempregado: "não",
      tempo_desempregado: "N/A",
      bicos: "sim",
      cadUnico: "não",
      mais_alguem_da_familia_trabalha: "sim",
      recebe_beneficio_social: "sim",
      beneficio_social: "Bolsa Família",
      valor_beneficio_social: "R$ 300,00",
      recebe_beneficio_eventual: "não",
      beneficio_eventual: "",
      recebe_auxilio_terceiros: "sim",
      valor_auxilio_terceiros: "R$ 200,00",
      quanto_ganha: "R$ 2.500,00",
      valor_total_familia: "R$ 4.500,00",
      renda_per_capta: "R$ 1.500,00",
      experiencias_profissionais: "Experiência em administração e vendas.",
      conhece_programa: "sim",
      como_conhece_programa: "Através de amigos que participaram do programa.",
      questao_assiduidade: "Ótima",
      questao_pontualidade: "Excelente",
      questao_responsabilidade: "Muito responsável",
      questao_interacao: "Bom relacionamento com colegas de trabalho.",
      pontuacao: "125",
      status: "Ativo",
      evolucoes: [
        {
          id: "01",
          titulo: "Promovido a supervisor",
          resumo:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam condimentum purus sit amet ante volutpat luctus. Donec porta rhoncus dolor, at posuere ex suscipit eu. Suspendisse sollicitudin lorem sit amet metus euismod, ut gravida nisi vehicula. Curabitur tincidunt justo in vestibulum tincidunt. Vivamus eu fringilla eros, sit amet vehicula dui. Morbi eu sem nec odio dapibus pulvinar. ",
          data: "2022-02-10",
          funcionario: "Lucas Aguilar",
        },
        {
          id: "02",
          funcionario: "Lucas Aguilar",
          titulo: "Concluiu curso de gestão de projetos",
          resumo:
            "João concluiu com êxito um curso de gestão de projetos, expandindo suas habilidades e contribuições para a empresa.",
          data: "2024-01-21",
        },
      ],
    }
]

export default cadastros;